name: Build and push latest image if needed

on:
  pull_request:
    branches:
      - main
      - release-*
      - workflow-test
  push:
    branches:
      - main
      - release-*
      - workflow-test

jobs:
  check-clickhouse-monitor-changes:
    name: Check whether clickhouse-monitor image needs to be built based on diff
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: antrea-io/has-changes@v2
      id: check_diff
      with:
        paths-ignore: build/yamls/* docs/* hack/* plugins/grafana-sankey-plugin/* *.md
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  build-clickhouse-monitor:
    needs: check-clickhouse-monitor-changes
    if: ${{ needs.check-clickhouse-monitor-changes.outputs.has_changes == 'yes' || github.event_name == 'push' }}
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build clickhouse-monitor Docker image
      run: make clickhouse-monitor
    - name: Push clickhouse-monitor Docker image to registry
      if: ${{ github.repository == 'yanjunz97/theia' && github.event_name == 'push' && github.ref == 'refs/heads/workflow-test' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push aurorazhou/theia-clickhouse-monitor:latest
